In [1]:
import numpy as np

In [129]:
# Logic: matrix multiplication psuedocode plus use built in zeros function

# def matrix_product(A,B):
#     if A.shape[1] != B.shape[0]:
#         return("cannot multiply")
#     else:
#         output = np.zeros((int(A.shape[0]), int(B.shape[1])))
#         TB = B.T
#         for ra in range(int(A.shape[0])):
#             for cb in range(int(B.shape[1])):
#                 for _ in range(int(B.shape[0])):
#                     output[ra][cb] = output[ra][cb]+(A[ra][_] * B[_][cb])
#         return output
                

In [123]:
#TEST CASE 1

# X = np.array([[1,2,3],[4,5,6]])
# print(X.shape)
# Y = np.array([[1,1],[1,1],[1,1]])
# print(Y.shape)

# print(matrix_product(X,Y))
# print(np.matmul(X,Y))

(2, 3)
(3, 2)
[[ 6.  6.]
 [15. 15.]]
[[ 6  6]
 [15 15]]


In [125]:
#TEST CASE 2

# X = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(X.shape)
# Y = np.array([[1,1],[1,1],[1,1]])
# print(Y.shape)

# print(matrix_product(X,Y))
# print(np.matmul(X,Y))

(3, 3)
(3, 2)
[[ 6.  6.]
 [15. 15.]
 [24. 24.]]
[[ 6  6]
 [15 15]
 [24 24]]


In [127]:
#TEST CASE 3 (should not work)

# X = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(X.shape)
# Y = np.array([[1,1],[1,1],[1,1], [1,1]])
# print(Y.shape)

# print(matrix_product(X,Y))
# print(np.matmul(X,Y))

(3, 3)
(4, 2)
cannot multiply


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)